Emma Duncan

7198831

In [12]:
import numpy as np
import math
from matplotlib import pyplot as plt

In [2]:
#tridiagonal solver from hw 4
def tridiag(A,b):
    n = len(A)
    U = np.zeros((n,n))
    L = np.zeros((n,n))
    y = np.zeros((n,1))
    x = np.zeros((n,1))
    U[0][0] = A[0][0]
    for j in range (0,n-1):
        L[j+1][j] = A[j+1][j]/U[j][j]
        U[j+1][j+1] = (A[j+1][j+1])-(L[j+1][j]*A[j][j+1])
        U[j][j+1] = A[j][j+1]
        L[j][j] = 1
    L[n-1][n-1]=1
    y[0][0] = b[0][0]
    for i in range (1,n):
        y[i][0] = b[i][0] - L[i][i-1]*y[i-1][0]     
    x[n-1][0]=y[n-1][0]/U[n-1][n-1]
    for k in range (n-2,-1,-1):
        x[k][0] = (y[k][0]-A[k][k+1]*x[k+1][0])/U[k][k]
    return(x)     

In [3]:
def jacobi(N):
    #create matricies A and b based on given boundary value probelm
    #code adapted from hw 4
    A = np.zeros((N+1,N+1))
    b = np.zeros((N+1,1))
    h = 1/N
    A[0][0]=1 
    A[N][N]=1
    for i in range(1,N):
        A[i][i-1] = -1/(h**2)
        A[i][i] = (2/(h**2))+(math.pi**2)
        A[i][i+1] = -1/(h**2)
        b[i][0] = 2*(math.pi**2)*math.sin(math.pi*(i/N))
        
    #create M
    M = np.zeros((N+1,N+1))
    x = np.zeros((N+1,1))
    tol = h*0.1
    iterations = 0 
    for j in range (0,N+1):
        M[j][j] = A[j][j]
        
    #create N matrix
    NN = -1*(A-M)
    
    #plug into equation to solve for x
    for i in range (0,N**N):
        x_i = x
        c = np.dot(NN,x_i)+b
        x_ii = tridiag(M,c)
        g = np.linalg.norm(b-np.dot(A,x_i))
#check tolerance
        if np.linalg.norm(b-np.dot(A,x_ii))<= tol:
            x = x_ii
            break

        else:
            x = x_ii
            iterations += 1
    return(x, iterations)  

In [4]:
jacobi(50)

(array([[ 0.        ],
        [ 0.06279958],
        [ 0.12535131],
        [ 0.18740834],
        [ 0.24872576],
        [ 0.30906157],
        [ 0.36817765],
        [ 0.42584071],
        [ 0.48182317],
        [ 0.53590409],
        [ 0.58787004],
        [ 0.63751594],
        [ 0.68464585],
        [ 0.72907378],
        [ 0.77062439],
        [ 0.80913369],
        [ 0.84444972],
        [ 0.87643308],
        [ 0.90495757],
        [ 0.9299106 ],
        [ 0.9511937 ],
        [ 0.96872288],
        [ 0.98242894],
        [ 0.99225781],
        [ 0.99817069],
        [ 1.00014425],
        [ 0.99817069],
        [ 0.99225781],
        [ 0.98242894],
        [ 0.96872288],
        [ 0.9511937 ],
        [ 0.9299106 ],
        [ 0.90495757],
        [ 0.87643308],
        [ 0.84444972],
        [ 0.80913369],
        [ 0.77062439],
        [ 0.72907378],
        [ 0.68464585],
        [ 0.63751594],
        [ 0.58787004],
        [ 0.53590409],
        [ 0.48182317],
        [ 0

In [5]:
jacobi(100)

(array([[ 0.        ],
        [ 0.03141183],
        [ 0.06279265],
        [ 0.09411151],
        [ 0.12533749],
        [ 0.15643978],
        [ 0.18738768],
        [ 0.21815065],
        [ 0.24869833],
        [ 0.27900058],
        [ 0.30902749],
        [ 0.33874942],
        [ 0.36813706],
        [ 0.39716138],
        [ 0.42579375],
        [ 0.45400592],
        [ 0.48177004],
        [ 0.5090587 ],
        [ 0.53584499],
        [ 0.56210247],
        [ 0.58780522],
        [ 0.61292787],
        [ 0.63744564],
        [ 0.66133433],
        [ 0.68457036],
        [ 0.7071308 ],
        [ 0.72899339],
        [ 0.75013655],
        [ 0.77053941],
        [ 0.79018185],
        [ 0.80904447],
        [ 0.82710866],
        [ 0.8443566 ],
        [ 0.86077126],
        [ 0.87633644],
        [ 0.89103679],
        [ 0.90485778],
        [ 0.9177858 ],
        [ 0.92980806],
        [ 0.94091272],
        [ 0.95108882],
        [ 0.9603263 ],
        [ 0.96861606],
        [ 0

N=50 took 2737 iterations, while N=100 took 12003 iterations. It makes sense that a larger N value would require more interations to achieve the desired accuracy.

In [6]:
def GS(N):
    #create matricies A and b based on given boundary value probelm
    #code adapted from hw 4
    A = np.zeros((N+1,N+1))
    b = np.zeros((N+1,1))
    h = 1/N
    A[0][0]=1 
    A[N][N]=1
    for i in range(1,N):
        A[i][i-1] = -1/(h**2)
        A[i][i] = (2/(h**2))+(math.pi**2)
        A[i][i+1] = -1/(h**2)
        b[i][0] = 2*(math.pi**2)*math.sin(math.pi*(i/N))
        
    #create M
    M = np.zeros((N+1,N+1))
    x = np.zeros((N+1,1))
    tol = h*0.1
    iterations = 0 
    for j in range (0,N+1):
        for i in range (0,j+1):
            M[j][i] = A[j][i]
            
    #create N matrix
    NN = -1*(A-M)

    #plug into equation to solve for x
    for i in range (0,N**N):
        x_i = x
        c = np.dot(NN,x_i)+b
        x_ii = tridiag(M,c)
        if np.linalg.norm(b-np.dot(A,x_ii))<= tol:
            x = x_ii
            break
        else:
            x = x_ii
            iterations += 1

    return(x, iterations)
        

In [7]:
GS(50)

(array([[ 0.        ],
        [ 0.06279946],
        [ 0.12535109],
        [ 0.18740802],
        [ 0.24872535],
        [ 0.30906109],
        [ 0.36817712],
        [ 0.42584012],
        [ 0.48182254],
        [ 0.53590344],
        [ 0.58786938],
        [ 0.63751527],
        [ 0.6846452 ],
        [ 0.72907314],
        [ 0.77062378],
        [ 0.80913312],
        [ 0.84444919],
        [ 0.87643261],
        [ 0.90495716],
        [ 0.92991025],
        [ 0.95119342],
        [ 0.96872267],
        [ 0.98242881],
        [ 0.99225776],
        [ 0.99817072],
        [ 1.00014435],
        [ 0.99817088],
        [ 0.99225807],
        [ 0.98242928],
        [ 0.96872329],
        [ 0.95119418],
        [ 0.92991114],
        [ 0.90495816],
        [ 0.87643373],
        [ 0.8444504 ],
        [ 0.80913441],
        [ 0.77062513],
        [ 0.72907454],
        [ 0.68464661],
        [ 0.63751669],
        [ 0.58787078],
        [ 0.5359048 ],
        [ 0.48182385],
        [ 0

In [8]:
GS(100)

(array([[ 0.        ],
        [ 0.03141182],
        [ 0.06279263],
        [ 0.09411148],
        [ 0.12533745],
        [ 0.15643973],
        [ 0.18738762],
        [ 0.21815058],
        [ 0.24869826],
        [ 0.2790005 ],
        [ 0.3090274 ],
        [ 0.33874933],
        [ 0.36813696],
        [ 0.39716128],
        [ 0.42579365],
        [ 0.45400581],
        [ 0.48176992],
        [ 0.50905859],
        [ 0.53584488],
        [ 0.56210235],
        [ 0.58780509],
        [ 0.61292775],
        [ 0.63744552],
        [ 0.6613342 ],
        [ 0.68457023],
        [ 0.70713068],
        [ 0.72899327],
        [ 0.75013643],
        [ 0.7705393 ],
        [ 0.79018174],
        [ 0.80904436],
        [ 0.82710856],
        [ 0.8443565 ],
        [ 0.86077116],
        [ 0.87633635],
        [ 0.8910367 ],
        [ 0.9048577 ],
        [ 0.91778572],
        [ 0.92980799],
        [ 0.94091266],
        [ 0.95108876],
        [ 0.96032625],
        [ 0.96861601],
        [ 0

For the Gauss-Seidel method, N=50 required 1369 iterations, while N=100 required 6002 iterations. This is significantly less than the Jacobi iteration method, which makes sense since the Gauss-Seidel converges a lot faster. 